# This workflow will build a Java project with Gradle and push a new docker image to docker hub
name: Build and Push Image to DockerHub

on:
  push:
    branches: [ master ]
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.DOCKER }}
      -
        name: Checkout new changes
        uses: actions/checkout@v2
        with:
          java-version: 1.8
          fetch-depth: 0
      -
        name: Setup GitVersion action
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      -
        name: Execute GitVersion action
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      -
        name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: 'VulnerableApp-${{ steps.gitversion.outputs.semver }}'
          tag_name: '${{ steps.gitversion.outputs.semver }}'
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      -
        name: Build with Gradle and Push
        run: |
          ./gradlew jib \
          -Djib.to.tags='latest',$GITVERSION_SEMVER