# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: get-archive
      uses: actions/download-artifact@v3
      with:
          name: VulnerableApp-1.0.0.jar
      # run the pipeline scan action
    - name: pipeline-scan action step
      id: pipeline-scan
      uses: veracode/Veracode-pipeline-scan-action@v1.0.8
      with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          file: "VulnerableApp-1.0.0.jar"
